# Generated by Django 4.0.4 on 2022-05-14 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=300, unique=True)),
                ('country_flag', models.ImageField(blank=True, null=True, upload_to='media/country_flag')),
            ],
            options={
                'ordering': ('country',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=200)),
                ('birth_day', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.nationality')),
            ],
            options={
                'ordering': ('-birth_day',),
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('award', models.DecimalField(decimal_places=0, max_digits=9)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.player')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
