# Generated by Django 4.0.4 on 2022-05-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='player',
        ),
        migrations.AddField(
            model_name='competition',
            name='players',
            field=models.ManyToManyField(related_name='competitions', to='games.player'),
        ),
    ]
